### ISSUE TITLE
Log SPAM

### ISSUE THREAD

**Issue by philcanman** [archerne/hastarlink#10] opened 2023-01-05 18:04 UTC
I was wondering if there is a way to stop the polling data from showing up in the HA logs?  It post about every second and makes it hard to view other issues.

**Comment by archerne** [comment] 2023-01-05 20:35
@philcanman I don't currently have any logs in my HA logs from starlink. Do you have your logger turned on all of HA to higher than `info`?

**Comment by philcanman** [comment] 2023-01-12 16:04
Sorry I was not clear here.  I am referring to the HA container logs.  Not sure if I am able to switch the log level there.

**Comment by leadZERO** [comment] 2023-02-16 15:50
I noticed the same very verbose logging on my HA/docker. I think https://github.com/archerne/hastarlink/pull/11 fixes this.

I looked for a way to not have to modify dish_grpc_text.py since it's really imported from the other source. However, I think the root of the problem is that it currently printing to standard out AND returning the lines in an array. Unfortunately we depend on one of those functions but can't separate them without modifying the file...

Thoughts?

**Comment by archerne** [comment] 2023-02-16 16:32
I just pushed a fix, can you check and see if that solved anything for you? I removed my calls to the grpc_text python file, those were old files before i integrated the core library and I hadn't taken the time to update them yet. I changed it instead to actually call the core library to get the status data and the location data. Hopefully that eliminates some of the Log spam and it simplifies the code as well.

**Comment by leadZERO** [comment] 2023-02-17 15:09
Looks fixed!

**Comment by archerne** [comment] 2023-03-13 15:55
Fixed with commit 9d49bae

**Closed by archerne** 2023-03-13 15:55 UTC
